from typing import Dict, Any
import datetime

class ReportGenerator:
    def format_to_markdown(self, content_body: str, strategy: Any, validation_status: bool) -> str:
        """Wraps the LLM output in a standard M&A report format."""
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        validation_tag = "✅ VERIFIED" if validation_status else "⚠️ VALIDATION FAILED"
        
        report = f"""# M&A Due Diligence Report
**Date:** {timestamp}
**Target Objective:** {strategy.objective}
**Status:** {validation_tag}

## Executive Summary
{content_body}

## Methodology & Traceability
- **Graph Source:** Neo4j (Temporal Snapshot)
- **Financial Models:** Deterministic (Cost/Revenue Synergy, Risk Score)
- **Reasoning Engine:** Ollama (Llama 3 70B Class)

---
*Generated by AI Reasoning Platform. All claims cited.*
"""
        return report

    def save_report(self, report_content: str, filename: str = "report.md"):
        with open(filename, "w") as f:
            f.write(report_content)
