import datetime
from typing import Dict, Any


REPORT_TITLES = {
    "risk_analysis": "Risk Analysis Report",
    "synergy_report": "Synergy & Opportunities Report",
    "valuation_summary": "Valuation Summary Report",
    "conclusion_report": "Executive Conclusion Report",
}


class ReportGenerator:
    def format_to_markdown(
        self,
        reports: Dict[str, str],
        strategy: Any,
        validation_status: bool,
        deal_type: str = "Acquisition",
        company_a_name: str = "Company A",
        company_b_name: str = "Company B",
    ) -> Dict[str, str]:
        """
        Wraps each LLM report in a standard M&A report header.
        Returns a dict mapping report_key -> formatted markdown string.
        """
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        validation_tag = "✅ VERIFIED" if validation_status else "⚠️ VALIDATION FAILED"

        formatted: Dict[str, str] = {}
        for key, content in reports.items():
            title = REPORT_TITLES.get(key, key.replace("_", " ").title())
            formatted[key] = f"""# {title}
**Deal:** {deal_type.capitalize()} — {company_a_name} &amp; {company_b_name}  
**Date:** {timestamp}  
**Strategic Objective:** {strategy.objective}  
**Status:** {validation_tag}

---

{content}

---

## Methodology & Traceability
- **Companies:** {company_a_name} &amp; {company_b_name}
- **Document Sources:** Company A & B uploaded documents
- **Graph Source:** Neo4j (Temporal Snapshot)
- **Reasoning Engine:** Ollama (`qwen3.5:397b-cloud`)

*Generated by Nexus M&A AI Platform. All claims grounded in provided data.*
"""
        return formatted

    def save_report(self, report_content: str, filename: str = "report.md"):
        with open(filename, "w") as f:
            f.write(report_content)
